### ISSUE TITLE
Crash on launch on Atmosphere 10.2

### ISSUE THREAD

**Issue by chicken-noodle-chris** [H0neyBadger/chiaki#2]
**Environment**
 - OS/Distribution: Atmosphere 10.2
 - Hardware: Switch

**Describe the bug**
Can't launch on switch. Tried running from the homebrew menu (injecting it through a game so it has full resources available, rather than going through album), and get instant crash. Is there a resources folder required or anything other than the .nro?

**To Reproduce**
1. Copy .nro to switch folder on hacked switch on Atmosphere 10.2
2. Attempt to launch

**Expected behavior**
App run

**Comment by ShinKaz** [comment]
well, same here, and I am on 9.1.0

**Comment by carbon658** [comment]
Have you created the chiaki.conf file and placed it in the same folder as the chiaki.nro file?

**Comment by chicken-noodle-chris** [comment]
> Have you created the chiaki.conf file and placed it in the same folder as the chiaki.nro file?

No, where can I find info on that? There's no wiki, no instructions on the release, and the readme is the main Chiaki readme with no mention of switch.

**Comment by carbon658** [comment]
https://gbatemp.net/threads/chiaki-ps4-remote-play-homebrew.564553/

**Comment by chicken-noodle-chris** [comment]
Thank you, that helped. Didn't realize the readme was under the switch folder. Do you know what are /how to get rp_key and rp_regist_key? They are mentioned in that thread but not the readme but there is nothing about what they are or where to get them

**Comment by H0neyBadger** [comment]
hello, 
I'm so sorry, I completely missed your issue. 
I'm not checking github's gui really often.
rp_regist_key and rp_key are created during the registration. 
@krazykhris875 did you manage to run the homebrew with your conf ?
@ShinKaz the 9.1.0 should not be a problem. What check have you done so far ?

@carbon658 thank you a lot for your help.

I'm not planning to leave the chiaki switch version as is. I'm working on GUI to simplify this process. 
At the beginning this version were not intended for all user (only a test preview). 
I'm working on it on my spare time. That's difficult to stay focus on chiaki project after a full day/week of work.

**Comment by ShinKaz** [comment]
Thanks, I got it to work with the info you gave us ^^

I use it with an AC router and a PS4Pro connected on a gigabit port. (same room) tried 1080p60, 1080p30, 720p30, 540p30, had the same result, fine for a few secs then very heavy graphical issues on screen, looking forward to testing next releases :)

**Comment by MrPalloncini** [comment]
Same here, the streaming goes fine but in open areas it starts lagging and making graphical issues

**Comment by carbon658** [comment]
The best place to look is at the GBATemp thread. For stability you should
overclock slightly. There is a lot of good information on the forum thread.

**Comment by H0neyBadger** [comment]
Hi,
there is serious performances issue currently. Gbatemp user managed to find
a solution to it by using Overclock. As far as I know, there is no hardware
acceleration available on switch to decode h.264. And every test I ve made
so far has failed. You may follow gbatemp users advice if you want to.
@hippydave made an overclock forwarded to chiaki.nro
https://gbatemp.net/threads/chiaki-ps4-remote-play-homebrew.564553/page-4
It solves basic 720p30fps configuration.
