### ISSUE TITLE
Network performance in horizon undocked

### ISSUE THREAD

**Issue by ralsim** [H0neyBadger/chiaki#3]
So I have built from latest source in Ubuntu L4T and devkit I don't know enough about the horizon OS to understand the problem so making a guess

All testing is undocked standard clocks
PS4 on 1gbit Lan
WiFi on 5g

L4T network performance is great it's very playable but in horizon it stutters glitches audio lags.

Is it possible horizon puts the WiFi chip into low power so your not getting full speed.

I have tested the performance of the network speed using FTP and getting about 200k in Ubuntu L4T but FTP in goldleaf I get around 40k to 50k.

**Comment by H0neyBadger** [comment]
hi @ralsim. 
just for my knowledge, what is the standard clocks on L4T ?

I identified the bottelneck in the h264 (libvacodec). 
As far as i know there is no Hardware acceleration on it. 
that cause graphical glitch on dynamic images.

regarding the wifi capabilities.
I know that usual wifi AP are able to emit on 2.4ghz and 5ghz simultaneously.
are you sure you are running on 802.11ac 5ghz from horizon?

I'm using 5g wifi without issue so far (but I never benchmarked my network).

**Comment by ralsim** [comment]
2.4 is disabled on my router it only broadcasts on 5g.

I suspect it's the vulkan/opengl driver in L4T that gives it the advantage possibly but only speculating..

L4T has CPU scaling so will go to full 1.7ghz if needed I have yet to monitor CPU usage with top while running ubuntu chiaki I might get time tonight. But let's assume it's using it at full scale

But network speed tests indicate horizon is not performing the same as Ubuntu. I will do some proper investigation into this but I don't know how to in horizon other than use FTP in Ubuntu it's easy I need to learn more about horizon maybe I should look into developing a network test tool. Again this could be down to CPU bottleneck as the file transfer may be slow due to CPU throttling in horizon as I'm running standard clocks in horizon

Have you compared the Ubuntu build compared to horizon build the difference is pretty obvious

**Comment by H0neyBadger** [comment]
to be honest I never tried LT4. 
for your test you may try to edit the following base: 
https://github.com/H0neyBadger/switch_samples/tree/master/sample_threads
with the python echo server you might be able to calculate: data loss, jitter, latency, bandwidth ...

I m closing this issue since it's not directly related to chiaki. I hope you will understand. 
feel free to share your results on this issue or on gbatemp.
I m interested by your results.
